server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log # modify to point at your application log file
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*log # modify to point at your application log file
  - targets:
      - localhost
    labels:
      job: docker_nginx
      __path__: /home/**/*.nginx.log # modify to point at your application log file
